modLoader="javafml"
loaderVersion="[43,)"
license="Mozilla Public License 2.0"

[[mods]]
issueTrackerURL="https://github.com/termSlime/featured-master/issues"
modId="featuredmaster"
version="1.0.0"
displayName="FeaturedMaster"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://0micro.github.io"
logoFile="logo.png"
authors="user, 0micro, MCreator"
description='''
This mod Adds Things
'''

[[dependencies.featuredmaster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.featuredmaster]]
    modId="etf"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.featuredmaster]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.featuredmaster]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.featuredmaster]]
    modId="reauth"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

